#!/bin/bash
# VINAYAKA TRANSPORT - Supabase Setup Automation Script
# This script helps create and configure Supabase for production

echo "================================"
echo "VINAYAKA TRANSPORT - Setup"
echo "================================"
echo ""
echo "Step 1: Create Supabase Project"
echo "Visit: https://supabase.com/dashboard"
echo ""
echo "Step 2: Create new project with:"
echo "  - Name: vinayaka-transport"
echo "  - Region: Singapore (or your region)"
echo "  - Password: (generate strong password)"
echo ""
echo "Step 3: Wait for project initialization (2-3 minutes)"
echo ""
echo "Step 4: Get your credentials"
echo "  - Go to: Settings → API"
echo "  - Copy Project URL"
echo "  - Copy anon public key"
echo "  - Copy service_role secret key"
echo ""
echo "Step 5: Save credentials to environment"
echo ""
read -p "Enter your SUPABASE_URL: " SUPABASE_URL
read -p "Enter your SUPABASE_ANON_KEY: " SUPABASE_ANON_KEY
read -sp "Enter your SUPABASE_SERVICE_ROLE_KEY: " SUPABASE_SERVICE_ROLE_KEY
echo ""
echo ""

echo "Step 6: Creating database schema..."
echo "  - Go to SQL Editor in Supabase"
echo "  - Click 'New Query'"
echo "  - Copy entire content from: services/api/supabase/schema.sql"
echo "  - Paste into SQL editor"
echo "  - Click 'Run'"
echo ""
read -p "Press Enter after running the SQL schema..."

echo ""
echo "Step 7: Setting environment variables in Vercel..."
echo ""
echo "For API Service (vinayaka-transport-api):"
echo "  1. Go to: https://vercel.com/dashboard"
echo "  2. Select: vinayaka-transport-api project"
echo "  3. Settings → Environment Variables"
echo "  4. Add these 3 variables:"
echo "     SUPABASE_URL=$SUPABASE_URL"
echo "     SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY"
echo "     SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY"
echo "  5. Click Save and Redeploy"
echo ""

echo "For ALL Portals (admin, operations, rider, tracking):"
echo "  For each portal:"
echo "  1. Go to Vercel project"
echo "  2. Settings → Environment Variables"
echo "  3. Add: NEXT_PUBLIC_API_URL=https://vinayaka-transport-api.vercel.app"
echo "  4. Save and Redeploy"
echo ""

read -p "Press Enter after configuring all Vercel environment variables..."

echo ""
echo "✅ Setup Complete!"
echo ""
echo "Test your deployment:"
echo ""
echo "1. Check API health:"
echo "   curl https://vinayaka-transport-api.vercel.app/api/v1/health"
echo ""
echo "2. Visit Admin Portal:"
echo "   https://admin-portal-three-pink.vercel.app"
echo ""
echo "3. Visit Public Tracking:"
echo "   https://tracking-portal-nine.vercel.app"
echo ""
