#!/bin/bash

# Deployment instructions for Vercel

echo "Vinayaka Transport - Vercel Deployment Guide"
echo "============================================="
echo ""
echo "1. Install Vercel CLI:"
echo "   npm i -g vercel"
echo ""
echo "2. Login to Vercel:"
echo "   vercel login"
echo ""
echo "3. For Admin Portal:"
echo "   cd apps/admin-portal"
echo "   vercel"
echo ""
echo "4. For Operations Portal:"
echo "   cd apps/operations-portal"
echo "   vercel"
echo ""
echo "5. For Rider Portal:"
echo "   cd apps/rider-portal"
echo "   vercel"
echo ""
echo "6. For Tracking Portal:"
echo "   cd apps/tracking-portal"
echo "   vercel"
echo ""
echo "7. For API Service:"
echo "   cd services/api"
echo "   vercel --env SUPABASE_URL=your_url --env SUPABASE_SERVICE_ROLE_KEY=your_key"
echo ""
echo "Environment Variables to set in Vercel Project Settings:"
echo "  NEXT_PUBLIC_API_URL=https://api-project.vercel.app/api/v1"
echo "  SUPABASE_URL=your_supabase_url"
echo "  SUPABASE_ANON_KEY=your_anon_key"
echo "  SUPABASE_SERVICE_ROLE_KEY=your_service_role_key"
